name: Fetcher

on:
  push:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  fetch:
    name: rfcsubseries rfc fetching
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Install gem
        run: |
          gem install relaton-cli
      - name: Fetch documents
        run: |
          rm -rf data
          relaton fetch-data ietf-rfc-entries
      - name: Push data
        run: |
          echo `date` > flag.txt
          git config user.name ietf-bib-bot
          git config user.email gh-bib-bot@llc.ietf.org
          git add data flag.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m 'update documents' && git push)
